---

- name: Install Homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

# The homebrew module's "update_homebrew" option seems to update homebrew
# for every package which is unnecessarily slow.
# Instead we just do it once right here.
- name: Update homebrew
  homebrew:
    update_homebrew: yes

# TODO: This condition isn't working. The task isn't skipped,
# it runs but doesn't do anything.
- name: Add additional taps.
  homebrew_tap:
    name: "{{ item }}"
  with_items: "{{ homebrew_taps }}"
  when: homebrew_taps != ""
